AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  lambda authorizer
  
# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst

Globals:
  Function:
    Timeout: 10
    Runtime: nodejs10.x
  Api:
    Cors:
      AllowMethods: "'OPTIONS,GET,POST,PUT,DELETE'"
      AllowHeaders: "'Content-Type,X-Amz-Date,Authorization,X-Api-Key'"
      AllowOrigin: "'*'"
    Auth:
      Authorizers:
        LambdaTokenAuthorizer:
          FunctionArn: !GetAtt LambdaAuthorizerFunction.Arn

Resources: 
  LambdaAuthorizerFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: vwpmw-lambda-authorizer/
      Handler: index.handler
      Layers:
              - !Ref DependencyLayer
      Environment:
        Variables:
          COGNITO_AWS_REGION: eu-west-1
          COGNITO_USER_POOL_ID: <insert-user-pool-id>
          COGNITO_APP_CLIENT_ID: <cognito-app-client-id>
      Policies:
        - CloudWatchPutMetricPolicy: {}
        - DynamoDBCrudPolicy: 
            TableName: <insert-table-if-required>
 
  DependencyLayer:
        Type: AWS::Serverless::LayerVersion
        Properties:
            LayerName: lambda-authorizer-dependencies
            Description: Dependencies
            ContentUri: dependencies/
            CompatibleRuntimes:
              - nodejs10.x
            LicenseInfo: 'MIT'
            RetentionPolicy: Retain
Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  Api:
    Description: "API Gateway endpoint URL for Prod stage"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/"
